[package]
name = "rust-math-macro"
version = "0.1.0"
edition = "2024"

[dependencies]
quote = "1.0.40"
syn = { version = "2.0.100", features = ["full", "extra-traits", "parsing"]}

[lib]
proc-macro = true
