[package]
name = "rock-paper-scissor"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
rpassword = "7.3.1"
serde = { version = "1.0.207", features = ["derive"] }
serde_json = "1.0.124"