[package]
name = "screaming_hunter"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15.0"
bevy-inspector-egui = "0.28.1"
bevy_asset_loader = "0.22.0"
clap = { version = "4.5.23", features = ["derive"]}

[lib]
name = "plugins"
path = "src/lib.rs"
